## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.2, random_state = 4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [3]:
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [4]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.42


# Lasso with alpha = 0.5

In [5]:
lasso = linear_model.Lasso(alpha = 0.5)

lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)

In [6]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.08860117,  0.04829133, -0.01107435,  0.        , -0.        ,
        2.66101769, -0.00307949, -0.98440282,  0.25664031, -0.01593271,
       -0.73252329,  0.00884426, -0.59210164])

In [7]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 26.94


# Lasso with alpha = 1.0

In [8]:
lasso = linear_model.Lasso(alpha = 1.0)

lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)

In [9]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [10]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 28.95


# Lasso with alpha = 1.5

In [11]:
lasso = linear_model.Lasso(alpha = 1.5)

lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)

In [12]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.04138351,  0.04153305, -0.        ,  0.        , -0.        ,
        0.        ,  0.02737094, -0.459279  ,  0.20038596, -0.01443953,
       -0.63976208,  0.00652437, -0.77489078])

In [13]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 32.00


# Ridge with alpha = 0.5

In [18]:
ridge = linear_model.Ridge(alpha = 0.5)

ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)

In [ ]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
ridge.coef_

In [ ]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

In [ ]:
# Ridge with alpha = 1.0

# Ridge with alpha = 1.5

In [14]:
ridge = linear_model.Ridge(alpha = 1.5)

ridge.fit(x_train, y_train)
y_pred = ridge.predict(x_test)

In [16]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
ridge.coef_

array([-0.11174732,  0.04818599, -0.03130445,  2.87083034, -7.6513143 ,
        3.93304603, -0.01877384, -1.40862269,  0.27151864, -0.01402211,
       -0.81455911,  0.00923543, -0.46922271])

In [17]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.85
